/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import Model.AddressRepo;
import Model.EcoSystem;
import Model.EnterPrise;
import Model.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author venkat
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */

      private JPanel upperConatiner;
      private EcoSystem eco;
      private AddressRepo addresslist;
    public ManageEnterpriseJPanel(JPanel userContainer,EcoSystem eco) {
        initComponents();
        this.upperConatiner = userContainer;
        this.eco = eco;
        addresslist =new AddressRepo();
        populateTable();
        populateComboBox();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networklabel = new javax.swing.JLabel();
        CmbNetkitem1 = new javax.swing.JComboBox();
        enterprisetypeLabel = new javax.swing.JLabel();
        CombEnterpriseitem2 = new javax.swing.JComboBox();
        nameLabel1 = new javax.swing.JLabel();
        textfield1 = new javax.swing.JTextField();
        ButtonBack = new javax.swing.JButton();
        ButtonSubmit = new javax.swing.JButton();
        MainLabel1 = new javax.swing.JLabel();
        jpanelscroll1 = new javax.swing.JScrollPane();
        nameTbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 204, 255));

        networklabel.setText("Network:");

        CmbNetkitem1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enterprisetypeLabel.setText("Enterprise Type:");

        CombEnterpriseitem2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nameLabel1.setText("Name:");

        textfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield1ActionPerformed(evt);
            }
        });

        ButtonBack.setBackground(new java.awt.Color(0, 51, 153));
        ButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBack.setText("<< Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        ButtonSubmit.setBackground(new java.awt.Color(0, 51, 153));
        ButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R.png"))); // NOI18N
        ButtonSubmit.setText("Submit");
        ButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitActionPerformed(evt);
            }
        });

        MainLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        MainLabel1.setForeground(new java.awt.Color(0, 51, 153));
        MainLabel1.setText("Manage Enterprise");

        nameTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Network", "Type"
            }
        ));
        jpanelscroll1.setViewportView(nameTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(452, 452, 452)
                                        .addComponent(networklabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(453, 453, 453)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(enterprisetypeLabel)
                                            .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(453, 453, 453)
                                .addComponent(ButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CombEnterpriseitem2, 0, 137, Short.MAX_VALUE)
                                .addComponent(CmbNetkitem1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textfield1))
                            .addComponent(ButtonSubmit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(MainLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(MainLabel1)
                .addGap(81, 81, 81)
                .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbNetkitem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networklabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterprisetypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CombEnterpriseitem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield1ActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        upperConatiner.remove(this);
        Component[] cmpArray = upperConatiner.getComponents();
        Component component= cmpArray[cmpArray.length-1];
        SystemAdminWorkAreaJPanel sysAdmin = (SystemAdminWorkAreaJPanel) component;
        sysAdmin.populateTreewithData();
        CardLayout crd = (CardLayout) upperConatiner.getLayout();
        crd.previous(upperConatiner);// TODO add your handling code here:
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubmitActionPerformed
        Network network = (Network) CmbNetkitem1.getSelectedItem();
        EnterPrise.EntType type = (EnterPrise.EntType) CombEnterpriseitem2.getSelectedItem();
        System.out.println(CombEnterpriseitem2.getSelectedItem());
        if (network == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }
        String name = textfield1.getText();
        for (EnterPrise e: network.getEnterpriseRepo().getEnterpRepo()) {
            if (e.getOrgName().equals(name)) {
                JOptionPane.showMessageDialog(this, "Enterprise name already exists.Please select a different name.");
                return;
            }
        }
        EnterPrise enterprise = network.getEnterpriseRepo().AddEnterPrise(name, type);
          Model.Address adr = addresslist.insertAddress();
// adr address doesnot hace setEnterprise
        adr.setName(textfield1.getText());

        populateTable();        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonSubmit;
    private javax.swing.JComboBox CmbNetkitem1;
    private javax.swing.JComboBox CombEnterpriseitem2;
    private javax.swing.JLabel MainLabel1;
    private javax.swing.JLabel enterprisetypeLabel;
    private javax.swing.JScrollPane jpanelscroll1;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTable nameTbl;
    private javax.swing.JLabel networklabel;
    private javax.swing.JTextField textfield1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       DefaultTableModel model = (DefaultTableModel) nameTbl.getModel();
       model.setRowCount(0);
       for(Network ntw : eco.getNetworks()){
       for(EnterPrise ent : ntw.getEnterpriseRepo().getEnterpRepo()){
        Object[] row = new Object[4];
        row[0] = ent.getOrgName();
        row[1] = ntw.getNetwork_name();
        row[2] = ent.getEnterprise_type().getValue();
        row[3] = ent.getZip();
        model.addRow(row);
    }
}
  
    }

    private void populateComboBox() {
    // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
   CmbNetkitem1.removeAllItems();
CombEnterpriseitem2.removeAllItems();
for(Network ntw : eco.getNetworks()){
    CmbNetkitem1.addItem(ntw);
}
for (EnterPrise.EntType type : EnterPrise.EntType.values()){
    CombEnterpriseitem2.addItem(type);
}


    }

}
