/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import Model.Account;
import Model.EcoSystem;
import Model.Employee;
import Model.EnterPrise;
import Model.Network;
import Model.Role.Role_Admin;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author venkat
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
private JPanel userConatiner;
private EcoSystem eco;

    public ManageEnterpriseAdminJPanel(JPanel userContainer, EcoSystem eco) {
        initComponents();
       this.userConatiner = userContainer;
   this.eco = eco;
   populateTable();
populateNetworkComnBox();

   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernamelabel = new javax.swing.JLabel();
        jtextuser = new javax.swing.JTextField();
        passwordlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        jtextname = new javax.swing.JTextField();
        jpanelscroll1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        buttonback = new javax.swing.JButton();
        buttonsubmit = new javax.swing.JButton();
        networklabel = new javax.swing.JLabel();
        jtxtpwd = new javax.swing.JPasswordField();
        cmntnet = new javax.swing.JComboBox();
        jmain1 = new javax.swing.JLabel();
        enterpriselabel = new javax.swing.JLabel();
        comnter = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(153, 204, 255));

        usernamelabel.setText("Username:");

        jtextuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextuserActionPerformed(evt);
            }
        });

        passwordlabel.setText("Password:");

        namelabel.setText("Name:");

        jpanelscroll1.setOpaque(false);

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jpanelscroll1.setViewportView(tblEnterprise);

        buttonback.setBackground(new java.awt.Color(0, 51, 153));
        buttonback.setForeground(new java.awt.Color(255, 255, 255));
        buttonback.setText("<< Back");
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });

        buttonsubmit.setBackground(new java.awt.Color(0, 51, 153));
        buttonsubmit.setForeground(new java.awt.Color(255, 255, 255));
        buttonsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R.png"))); // NOI18N
        buttonsubmit.setText("Submit");
        buttonsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsubmitActionPerformed(evt);
            }
        });

        networklabel.setText("Network:");

        cmntnet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmntnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmntnetActionPerformed(evt);
            }
        });

        jmain1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jmain1.setForeground(new java.awt.Color(0, 51, 153));
        jmain1.setText("Manage Enterprise Admin");

        enterpriselabel.setText("Enterprise:");

        comnter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtextname))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriselabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comnter, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(networklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmntnet, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtextuser))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtpwd))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(buttonback, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(buttonsubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jmain1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jmain1)
                .addGap(47, 47, 47)
                .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmntnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriselabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonback, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonsubmit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtextuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextuserActionPerformed

    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbackActionPerformed
        userConatiner.remove(this);
        Component[] cmpArray = userConatiner.getComponents();
        Component component = cmpArray[cmpArray.length-1];
        SystemAdminWorkAreaJPanel sysWAJP = (SystemAdminWorkAreaJPanel) component;
        sysWAJP.populateTreewithData();
        CardLayout card = (CardLayout) userConatiner.getLayout();
        card.previous(userConatiner);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonbackActionPerformed

    private void buttonsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsubmitActionPerformed
        EnterPrise ent = (EnterPrise) comnter.getSelectedItem();
        String username = jtextuser.getText();
        String password = String.valueOf(jtxtpwd.getPassword());
        String name = jtextname.getText();
        for (Account ua: ent.getUserAccDir().getAccountList()) {
            if (ua.getUsrnm().equals(name)) {
                JOptionPane.showMessageDialog(this, "Username is already taken, please select a different username");
                return;
            }
        }
        Employee employee = ent.getEmpDir().AddEmployee(name);
        Account ua = ent.getUserAccDir().createUserAccount(username, password, employee, new Role_Admin());
        populateTable();// TODO add your handling code here:
    }//GEN-LAST:event_buttonsubmitActionPerformed

    private void cmntnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmntnetActionPerformed
        Network network =(Network) cmntnet.getSelectedItem();
        if(network != null){
            populateEnterpriseComboBox (network);
        }// TODO add your handling code here:
    }//GEN-LAST:event_cmntnetActionPerformed

    private void comnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comnterActionPerformed
        EnterPrise ent = (EnterPrise) comnter.getSelectedItem();
        if(ent != null){
            // TODO add your handling code here:
    }//GEN-LAST:event_comnterActionPerformed


}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonback;
    private javax.swing.JButton buttonsubmit;
    private javax.swing.JComboBox cmntnet;
    private javax.swing.JComboBox comnter;
    private javax.swing.JLabel enterpriselabel;
    private javax.swing.JLabel jmain1;
    private javax.swing.JScrollPane jpanelscroll1;
    private javax.swing.JTextField jtextname;
    private javax.swing.JTextField jtextuser;
    private javax.swing.JPasswordField jtxtpwd;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel networklabel;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JLabel usernamelabel;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
 // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();
model.setRowCount(0);
for(Network ntw : eco.getNetworks()){
    for(EnterPrise ent : ntw.getDirectoEnterpri().getEnterpList()){
        for(Account ua : ent.getUserAccDir().getAccountList()){
            Object[] row = new Object[3];
            row[0] = ent.getOrgName();
            row[1]= ntw.getNetwork_Name();
            row[2] = ua.getUsrnm();
            model.addRow(row);
        }
    }
}    }

    private void populateNetworkComnBox() {
        
 // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  cmntnet.removeAllItems();
        for (Network network : eco.getNetworks()){
            cmntnet.addItem(network);
        }


    }

    private void populateEnterpriseComboBox(Network network) {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
comnter.removeAllItems();
    for(EnterPrise enterprise : network.getDirectoEnterpri().getEnterpList()){
     comnter.addItem(enterprise);
System.out.println("I Came here");
}
    }
    


}
