/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import Model.Directory_Address;
import Model.EcoSystem;
import Model.EnterPrise;
import Model.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author venkat
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */

      private JPanel upperConatiner;
      private EcoSystem eco;
      private Directory_Address addresslist;
    public ManageEnterpriseJPanel(JPanel userContainer,EcoSystem eco) {
        initComponents();
        this.upperConatiner = userContainer;
        this.eco = eco;
        addresslist =new Directory_Address();
        populateTable();
        populateComboBox();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networklabel = new javax.swing.JLabel();
        comtlabel = new javax.swing.JComboBox();
        enterpriselabel1 = new javax.swing.JLabel();
        comenterprise = new javax.swing.JComboBox();
        namelabel = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        buttonback = new javax.swing.JButton();
        buttonsubmit = new javax.swing.JButton();
        mainlabel1 = new javax.swing.JLabel();
        jpanelscroll2 = new javax.swing.JScrollPane();
        nameTbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 204, 255));

        networklabel.setText("Network:");

        comtlabel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enterpriselabel1.setText("Enterprise Type:");

        comenterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        namelabel.setText("Name:");

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        buttonback.setBackground(new java.awt.Color(0, 51, 153));
        buttonback.setForeground(new java.awt.Color(255, 255, 255));
        buttonback.setText("<< Back");
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });

        buttonsubmit.setBackground(new java.awt.Color(0, 51, 153));
        buttonsubmit.setForeground(new java.awt.Color(255, 255, 255));
        buttonsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R.png"))); // NOI18N
        buttonsubmit.setText("Submit");
        buttonsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsubmitActionPerformed(evt);
            }
        });

        mainlabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        mainlabel1.setForeground(new java.awt.Color(0, 51, 153));
        mainlabel1.setText("Manage Enterprise");

        nameTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Network", "Type"
            }
        ));
        jpanelscroll2.setViewportView(nameTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jpanelscroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(452, 452, 452)
                                        .addComponent(networklabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(453, 453, 453)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(enterpriselabel1)
                                            .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(453, 453, 453)
                                .addComponent(buttonback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comenterprise, 0, 137, Short.MAX_VALUE)
                                .addComponent(comtlabel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt2))
                            .addComponent(buttonsubmit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(mainlabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(mainlabel1)
                .addGap(81, 81, 81)
                .addComponent(jpanelscroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comtlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networklabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriselabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comenterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonsubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbackActionPerformed
        upperConatiner.remove(this);
        Component[] cmpArray = upperConatiner.getComponents();
        Component component= cmpArray[cmpArray.length-1];
        SystemAdminWorkAreaJPanel sysAdmin = (SystemAdminWorkAreaJPanel) component;
        sysAdmin.populateTreewithData();
        CardLayout crd = (CardLayout) upperConatiner.getLayout();
        crd.previous(upperConatiner);// TODO add your handling code here:
    }//GEN-LAST:event_buttonbackActionPerformed

    private void buttonsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsubmitActionPerformed
        Network network = (Network) comtlabel.getSelectedItem();
        EnterPrise.EntType type = (EnterPrise.EntType) comenterprise.getSelectedItem();
        System.out.println(comenterprise.getSelectedItem());
        if (network == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }
        String name = txt2.getText();
        for (EnterPrise e: network.getDirectoEnterpri().getEnterpList()) {
            if (e.getOrgName().equals(name)) {
                JOptionPane.showMessageDialog(this, "Enterprise name already exists.Please select a different name.");
                return;
            }
        }
        EnterPrise enterprise = network.getDirectoEnterpri().AddEnterPrise(name, type);
          Model.Address adr = addresslist.insertAddress();
// adr address doesnot hace setEnterprise
        adr.setName(txt2.getText());

        populateTable();        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonback;
    private javax.swing.JButton buttonsubmit;
    private javax.swing.JComboBox comenterprise;
    private javax.swing.JComboBox comtlabel;
    private javax.swing.JLabel enterpriselabel1;
    private javax.swing.JScrollPane jpanelscroll2;
    private javax.swing.JLabel mainlabel1;
    private javax.swing.JTable nameTbl;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel networklabel;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       DefaultTableModel model = (DefaultTableModel) nameTbl.getModel();
       model.setRowCount(0);
       for(Network ntw : eco.getNetworks()){
       for(EnterPrise ent : ntw.getDirectoEnterpri().getEnterpList()){
        Object[] row = new Object[4];
        row[0] = ent.getOrgName();
        row[1] = ntw.getNetwork_Name();
        row[2] = ent.getEnterprise_type().getValue();
        row[3] = ent.getZip();
        model.addRow(row);
    }
}
  
    }

    private void populateComboBox() {
    // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
   comtlabel.removeAllItems();
comenterprise.removeAllItems();
for(Network ntw : eco.getNetworks()){
    comtlabel.addItem(ntw);
}
for (EnterPrise.EntType type : EnterPrise.EntType.values()){
    comenterprise.addItem(type);
}


    }







}
