/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import Model.EcoSystem;
import Model.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author venkat
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageNetworkJPanel
     */
public JPanel userContainer;
public EcoSystem eco;

    public ManageNetworkJPanel(JPanel userConatiner, EcoSystem eco) {
        initComponents();
this.userContainer =userConatiner;
this.eco = eco;
populateNetworkTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelscroll1 = new javax.swing.JScrollPane();
        nameTbl = new javax.swing.JTable();
        namelabel = new javax.swing.JLabel();
        jtxtfield1 = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        submitbutton = new javax.swing.JButton();
        jlabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        nameTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jpanelscroll1.setViewportView(nameTbl);

        namelabel.setText("Name:");

        backbutton.setBackground(new java.awt.Color(0, 51, 153));
        backbutton.setForeground(new java.awt.Color(255, 255, 255));
        backbutton.setText("<< Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        submitbutton.setBackground(new java.awt.Color(0, 51, 153));
        submitbutton.setForeground(new java.awt.Color(255, 255, 255));
        submitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R.png"))); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        jlabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(0, 51, 153));
        jlabel2.setText("Manage Network");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(357, 357, 357)
                                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(342, 342, 342)
                                .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitbutton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jlabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jlabel2)
                .addGap(73, 73, 73)
                .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        userContainer.remove(this);
        Component[] compArray = userContainer.getComponents();
        Component component = compArray[compArray.length-1];
        SystemAdminWorkAreaJPanel sysadminWrkPnl =(SystemAdminWorkAreaJPanel) component;
        sysadminWrkPnl.populateTreewithData();
        CardLayout crdLO = (CardLayout) userContainer.getLayout();
        crdLO.previous(userContainer); // TODO add your handling code here:
    }//GEN-LAST:event_backbuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        String networkName = jtxtfield1.getText();
        for (Network n: eco.getNetworks()) {
            if (n.getNetwork_Name().equals(networkName)) {
                JOptionPane.showMessageDialog(this, "Can not insert copies.");
                return;
            }
        }

//probable error;
        Network network = eco.addBuildedNetwork();
        network.setNetwork_Name(networkName);
        populateNetworkTable();// TODO add your handling code here:
    }//GEN-LAST:event_submitbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JScrollPane jpanelscroll1;
    private javax.swing.JTextField jtxtfield1;
    private javax.swing.JTable nameTbl;
    private javax.swing.JLabel namelabel;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables

    private void populateNetworkTable() {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

   DefaultTableModel model = (DefaultTableModel) nameTbl.getModel();
       model.setRowCount(0);
       for(Network network : eco.getNetworks()){
           Object[] row = new Object[1];
           row[0] = network.getNetwork_Name();
           model.addRow(row);
           
       }
      
    }
}
