/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import Model.Account;
import Model.EcoSystem;
import Model.Employee;
import Model.EnterPrise;
import Model.Network;
import Model.Role.Admin_Role;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author venkat
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
private JPanel userConatiner;
private EcoSystem eco;

    public ManageEnterpriseAdminJPanel(JPanel userContainer, EcoSystem eco) {
        initComponents();
       this.userConatiner = userContainer;
   this.eco = eco;
   populateTable();
populateNetworkComnBox();

   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        JtextfieldUser = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        JTextfieldName = new javax.swing.JTextField();
        jpanelscroll1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        ButtonBack = new javax.swing.JButton();
        ButtonSubmit = new javax.swing.JButton();
        networkLabel = new javax.swing.JLabel();
        JtextfieldPwd = new javax.swing.JPasswordField();
        ComNetitem = new javax.swing.JComboBox();
        jLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        Comenteritem1 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(153, 204, 255));

        usernameLabel.setText("Username:");

        JtextfieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextfieldUserActionPerformed(evt);
            }
        });

        passwordLabel.setText("Password:");

        nameLabel.setText("Name:");

        jpanelscroll1.setOpaque(false);

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jpanelscroll1.setViewportView(tblEnterprise);

        ButtonBack.setBackground(new java.awt.Color(0, 51, 153));
        ButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBack.setText("<< Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        ButtonSubmit.setBackground(new java.awt.Color(0, 51, 153));
        ButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R.png"))); // NOI18N
        ButtonSubmit.setText("Submit");
        ButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitActionPerformed(evt);
            }
        });

        networkLabel.setText("Network:");

        ComNetitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComNetitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComNetitemActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel.setForeground(new java.awt.Color(0, 51, 153));
        jLabel.setText("Manage Enterprise Admin");

        enterpriseLabel.setText("Enterprise:");

        Comenteritem1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Comenteritem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comenteritem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JTextfieldName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Comenteritem1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(networkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ComNetitem, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JtextfieldUser))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JtextfieldPwd))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(ButtonSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel)
                .addGap(47, 47, 47)
                .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComNetitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comenteritem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtextfieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtextfieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextfieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSubmit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JtextfieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextfieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextfieldUserActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        userConatiner.remove(this);
        Component[] cmpArray = userConatiner.getComponents();
        Component component = cmpArray[cmpArray.length-1];
        SystemAdminWorkAreaJPanel sysWAJP = (SystemAdminWorkAreaJPanel) component;
        sysWAJP.populateTreewithData();
        CardLayout card = (CardLayout) userConatiner.getLayout();
        card.previous(userConatiner);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubmitActionPerformed
        EnterPrise ent = (EnterPrise) Comenteritem1.getSelectedItem();
        String username = JtextfieldUser.getText();
        String password = String.valueOf(JtextfieldPwd.getPassword());
        String name = JTextfieldName.getText();
        for (Account ua: ent.getUserAccDir().getAccountList()) {
            if (ua.getUsernm().equals(name)) {
                JOptionPane.showMessageDialog(this, "Username is already taken, please select a different username");
                return;
            }
        }
        Employee employee = ent.getEmpRepo().AddEmployee(name);
        Account ua = ent.getUserAccDir().createUserAccount(username, password, employee, new Admin_Role());
        populateTable();// TODO add your handling code here:
    }//GEN-LAST:event_ButtonSubmitActionPerformed

    private void ComNetitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComNetitemActionPerformed
        Network network =(Network) ComNetitem.getSelectedItem();
        if(network != null){
            populateEnterpriseComboBox (network);
        }// TODO add your handling code here:
    }//GEN-LAST:event_ComNetitemActionPerformed

    private void Comenteritem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comenteritem1ActionPerformed
        EnterPrise ent = (EnterPrise) Comenteritem1.getSelectedItem();
        if(ent != null){
            // TODO add your handling code here:
    }//GEN-LAST:event_Comenteritem1ActionPerformed


}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonSubmit;
    private javax.swing.JComboBox ComNetitem;
    private javax.swing.JComboBox Comenteritem1;
    private javax.swing.JTextField JTextfieldName;
    private javax.swing.JPasswordField JtextfieldPwd;
    private javax.swing.JTextField JtextfieldUser;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jpanelscroll1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel networkLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
 // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();
model.setRowCount(0);
for(Network ntw : eco.getNetworks()){
    for(EnterPrise ent : ntw.getEnterpriseRepo().getEnterpRepo()){
        for(Account ua : ent.getUserAccDir().getAccountList()){
            Object[] row = new Object[3];
            row[0] = ent.getOrgName();
            row[1]= ntw.getNetwork_name();
            row[2] = ua.getUsernm();
            model.addRow(row);
        }
    }
}    }

    private void populateNetworkComnBox() {
        
 // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  ComNetitem.removeAllItems();
        for (Network network : eco.getNetworks()){
            ComNetitem.addItem(network);
        }


    }

    private void populateEnterpriseComboBox(Network network) {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
Comenteritem1.removeAllItems();
    for(EnterPrise enterprise : network.getEnterpriseRepo().getEnterpRepo()){
     Comenteritem1.addItem(enterprise);
System.out.println("I Came here");
}
    }
    


}
