/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Role_Pharmacy;

import Model.Account;
import Model.Drug_Store;
import Model.DrugPantryList;
import Model.EnterPrise;
import Model.Network;
import Model.Organization.Organization;
import Model.Organization.PharmacyOrganization;
import Model.WorkQueue.Pharmacy_WorkRequest;
import Model.WorkQueue.Supplier_WorkRequest;
import Model.WorkQueue.Work_Request;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshinichandrika
 */
public class WorkAreaPanel_Pharmacy extends javax.swing.JPanel {

    private Network network;
    private PharmacyOrganization op;
    private Organization orgz;
    private DrugPantryList dp;
    private EnterPrise enterprise;
    private Account acc;
    JPanel panel;

    /**
     * Creates new form WorkAreaPanel_Pharmacy
     */
    public WorkAreaPanel_Pharmacy(JPanel panel, Account acc, EnterPrise enterprise, PharmacyOrganization op, Network network) {
        initComponents();
        this.op=(PharmacyOrganization) op;
        this.panel=panel;
        this.network=network;
        this.enterprise=enterprise;
        this.dp= dp;
        this.acc=acc;
        arrangeRows();
        fillDocRows();
    }
    
    public void fillDocRows() {
        DefaultTableModel tab = (DefaultTableModel) tblDoc.getModel();
        tab.setRowCount(0);
        for (Work_Request wr : op.getWQ().getWorkRequestList()) {
            Object[] o = new Object[4];
            String drug = ((Pharmacy_WorkRequest) wr).getMedicationName();
            System.out.println("****" + drug);
            o[0] = drug;
            int num = ((Pharmacy_WorkRequest) wr).getQuantity();
            o[1] = num;
            o[2] = ((Pharmacy_WorkRequest) wr).getStatus();
            tab.addRow(o);
        }
    }
    
    public void arrangeRows() {

        int rc = tblPharmacy.getRowCount();
        DefaultTableModel tbl = (DefaultTableModel) tblPharmacy.getModel();
        for (int i = rc - 1; i >= 0; i--) {
            tbl.removeRow(i);
        }
        for (Drug_Store i : op.getDrugs()) {
            Object o[] = new Object[6];
            o[0] = i;
            o[1] = i.getSerialNo();
            o[2] = i.getQuantitypresent();
            o[3] = i.getQuantityneeded();
            o[4] = i.getReorderQuantity();
            o[5] = i.getReorderStatus();
            tbl.addRow(o);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeader = new javax.swing.JLabel();
        scrollPane1 = new javax.swing.JScrollPane();
        tblPharmacy = new javax.swing.JTable();
        buttonStatus = new javax.swing.JButton();
        labelSerialNumber = new javax.swing.JLabel();
        labelMedicineName = new javax.swing.JLabel();
        labelAvailableQuantity = new javax.swing.JLabel();
        labelReqQuantity = new javax.swing.JLabel();
        labelReorderLevel = new javax.swing.JLabel();
        txtfieldSerialNumber = new javax.swing.JTextField();
        txtfieldMedicine = new javax.swing.JTextField();
        txtfieldAvailableQuantity = new javax.swing.JTextField();
        txtfieldReqQuantity = new javax.swing.JTextField();
        txtfieldReorder = new javax.swing.JTextField();
        buttonBack = new javax.swing.JButton();
        buttonAddMedicine = new javax.swing.JButton();
        buttonDetails = new javax.swing.JButton();
        buttonReqs = new javax.swing.JButton();
        buttonViewReq = new javax.swing.JButton();
        labelDocTbl = new javax.swing.JLabel();
        scrollPane2 = new javax.swing.JScrollPane();
        tblDoc = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(0, 51, 153));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader.setText("PHARMACY MEDICINE INVENTORY LOG");
        add(labelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1069, -1));

        tblPharmacy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICINE NAME", "SERIAL NUMBER", "AVAILABLE QUANTITY", "REQUIRED QUANTITY", "REORDER LEVEL", "REORDER STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane1.setViewportView(tblPharmacy);

        add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1025, 80));

        buttonStatus.setBackground(new java.awt.Color(0, 51, 153));
        buttonStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonStatus.setForeground(new java.awt.Color(255, 255, 255));
        buttonStatus.setText("INVENTORY STATUS CHECK!");
        buttonStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStatusActionPerformed(evt);
            }
        });
        add(buttonStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 309, 38));

        labelSerialNumber.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelSerialNumber.setForeground(new java.awt.Color(0, 51, 153));
        labelSerialNumber.setText("SERIAL NUMBER:");
        add(labelSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 236, -1));

        labelMedicineName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelMedicineName.setForeground(new java.awt.Color(0, 51, 153));
        labelMedicineName.setText("MEDICNE NAME:");
        add(labelMedicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 236, -1));

        labelAvailableQuantity.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelAvailableQuantity.setForeground(new java.awt.Color(0, 51, 153));
        labelAvailableQuantity.setText("AVAILABLE QUANTITY:");
        add(labelAvailableQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 236, -1));

        labelReqQuantity.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelReqQuantity.setForeground(new java.awt.Color(0, 51, 153));
        labelReqQuantity.setText("REQUIRED QUANTITY:");
        add(labelReqQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 236, -1));

        labelReorderLevel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelReorderLevel.setForeground(new java.awt.Color(0, 51, 153));
        labelReorderLevel.setText("REORDER LEVEL:");
        add(labelReorderLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 236, -1));
        add(txtfieldSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 257, 25));
        add(txtfieldMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 257, 25));
        add(txtfieldAvailableQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 257, 25));
        add(txtfieldReqQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 257, 25));

        txtfieldReorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldReorderActionPerformed(evt);
            }
        });
        add(txtfieldReorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 257, 25));

        buttonBack.setBackground(new java.awt.Color(0, 51, 153));
        buttonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setText("<<BACK");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 138, -1));

        buttonAddMedicine.setBackground(new java.awt.Color(0, 51, 153));
        buttonAddMedicine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAddMedicine.setForeground(new java.awt.Color(255, 255, 255));
        buttonAddMedicine.setText("ADD MEDICINE");
        buttonAddMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddMedicineActionPerformed(evt);
            }
        });
        add(buttonAddMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 257, -1));

        buttonDetails.setBackground(new java.awt.Color(0, 51, 153));
        buttonDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDetails.setForeground(new java.awt.Color(255, 255, 255));
        buttonDetails.setText("VIEW DETAILS >>");
        buttonDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetailsActionPerformed(evt);
            }
        });
        add(buttonDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 309, 38));

        buttonReqs.setBackground(new java.awt.Color(0, 51, 153));
        buttonReqs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonReqs.setForeground(new java.awt.Color(255, 255, 255));
        buttonReqs.setText("VIEW REQUESTS");
        buttonReqs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReqsActionPerformed(evt);
            }
        });
        add(buttonReqs, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 309, 38));

        buttonViewReq.setBackground(new java.awt.Color(0, 51, 153));
        buttonViewReq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonViewReq.setForeground(new java.awt.Color(255, 255, 255));
        buttonViewReq.setText("VIEW REQUESTS FROM DOCTORS");
        add(buttonViewReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, 38));

        labelDocTbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDocTbl.setForeground(new java.awt.Color(0, 51, 153));
        labelDocTbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDocTbl.setText("View Requests from Doctor:");
        add(labelDocTbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 150, 1069, 35));

        tblDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICINE NAME", "QUANTITY", "STATUS"
            }
        ));
        scrollPane2.setViewportView(tblDoc);

        add(scrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 825, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStatusActionPerformed
        for(Drug_Store dp : op.getDrugs()){

            if(dp.getQuantitypresent()<=dp.getReorderQuantity()){
                if(!dp.getReorderStatus().equals("Y")){
                    Supplier_WorkRequest swr=new Supplier_WorkRequest();

                    dp.setReorderStatus("Y");
                    swr.setMedicationName(dp.getDrugName());
                    swr.setQuantity(dp.getQuantityneeded());
                    swr.setSender(acc);

                    acc.getWorkQ().getWorkRequestList().add(swr);
                    for(EnterPrise enterprise : network.getEnterpriseRepo().getEnterpRepo()){
                        System.out.println("***** Organization Name:" +enterprise.getOrgName());
                        for(Organization g : enterprise.getOrgaDirectory().getOrganizations()){
                            System.out.println("***** Organization Name:" +g.getOrgName());
                            if(g.getOrgName().equals("Supplier Organization")){
                                System.out.println("True");

                                System.out.println("***** organization Name"+g.getOrgName());

                                g.getWQ().getWorkRequestList().add(swr);
                            }
                        }

                    }

                }

            }
        }
        JOptionPane.showMessageDialog(null, "Status of inventory checked and updated!", "Warning", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonStatusActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        panel.remove(this);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonAddMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddMedicineActionPerformed
        Drug_Store dp=new Drug_Store();

        String pre=txtfieldAvailableQuantity.getText();
        try{
            Integer.parseInt(pre);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please provide valid data in Available Quantity");
            return;
        }
        dp.setDrugName(txtfieldMedicine.getText());
        int qp= Integer.parseInt(txtfieldAvailableQuantity.getText());
        dp.setQuantitypresent(qp);
        String sno=txtfieldSerialNumber.getText();
        try{
            Integer.parseInt(sno);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Serial Number must be integer!");
            return;
        }
        int sn= Integer.parseInt(txtfieldSerialNumber.getText());
        dp.setSerialNo(sn);
        String rc=txtfieldReqQuantity.getText();
        try
        {
            Integer.parseInt(rc);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Required quantity must be integer!");
            return;
        }
        int rt= Integer.parseInt(txtfieldReqQuantity.getText());
        dp.setQuantityneeded(rt);

        String ro=txtfieldReorder.getText();
        try
        {
            Integer.parseInt(ro);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Reorder level must be integer!");
            return;
        }
        int rl= Integer.parseInt(txtfieldReorder.getText());
        dp.setReorderQuantity(rl);
        op.addDrug(dp);
        dp.setReorderStatus("N");

        DefaultTableModel dtm =(DefaultTableModel) tblPharmacy.getModel();

        dtm.setRowCount(0);
        for(Drug_Store drp : op.getDrugs()){
            Object row[] = new Object[5];
            row[0] = drp;
            row[1] = drp.getSerialNo();
            row[2]= drp.getQuantitypresent();
            row[3]=drp.getQuantityneeded();
            row[4]= drp.getReorderQuantity();
            dtm.addRow(row);
        }

        JOptionPane.showMessageDialog(null, "Medicine Added Successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddMedicineActionPerformed

    private void buttonDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetailsActionPerformed
        int val = tblPharmacy.getSelectedRow();
        if(val<0){
            JOptionPane.showMessageDialog(null, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Drug_Store dp = (Drug_Store)tblPharmacy.getValueAt(val, 0);

        CardLayout c = (CardLayout) panel.getLayout();
        panel.add("UpdateEntryJPanel", new EntryPanel_Update(panel, acc, enterprise,dp));
        c.next(panel);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDetailsActionPerformed

    private void buttonReqsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReqsActionPerformed
        CardLayout c = (CardLayout) panel.getLayout();
        panel.add("ViewrequestJPanel", new RequestPanel_View( panel, acc, enterprise, orgz));
        c.next(panel);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReqsActionPerformed

    private void txtfieldReorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldReorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldReorderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddMedicine;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonDetails;
    private javax.swing.JButton buttonReqs;
    private javax.swing.JButton buttonStatus;
    private javax.swing.JButton buttonViewReq;
    private javax.swing.JLabel labelAvailableQuantity;
    private javax.swing.JLabel labelDocTbl;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelMedicineName;
    private javax.swing.JLabel labelReorderLevel;
    private javax.swing.JLabel labelReqQuantity;
    private javax.swing.JLabel labelSerialNumber;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JTable tblDoc;
    private javax.swing.JTable tblPharmacy;
    private javax.swing.JTextField txtfieldAvailableQuantity;
    private javax.swing.JTextField txtfieldMedicine;
    private javax.swing.JTextField txtfieldReorder;
    private javax.swing.JTextField txtfieldReqQuantity;
    private javax.swing.JTextField txtfieldSerialNumber;
    // End of variables declaration//GEN-END:variables
}
