/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Role_HospitalAdmin;

import Model.Account;
import Model.Employee;
import Model.EnterPrise;
import Model.Organization.Organization;
import Model.Role.Role;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshinichandrika
 */
public class ManagePanel_Account extends javax.swing.JPanel {
    
    private EnterPrise enterprise;
    private JPanel panel;

    /**
     * Creates new form ManagePanel_Account
     */
    public ManagePanel_Account(JPanel p, EnterPrise e) {
        initComponents();
        this.enterprise=e;
        this.panel=p;
        
        fillCmbOrg();
        fillRows();
    }
    
    public void fillCmbOrg() {
        cmbOrg1.removeAllItems();
        for (Organization o : enterprise.getOrgaDirectory().getOrganizations()) {
            cmbOrg1.addItem(o);
        }
    }

    public void fillRows() {
        DefaultTableModel m = (DefaultTableModel) tblAcc.getModel();
        m.setRowCount(0);
        for (Organization o : enterprise.getOrgaDirectory().getOrganizations()) {
            for (Account a : o.getUserAccDir().getAccountList()) {
                Object r[] = new Object[2];
                r[0] = a.getUsernm();
                r[1] = a.getRole();
                ((DefaultTableModel) tblAcc.getModel()).addRow(r);
            }
        }
    }

    public void fillCmbRole(Organization o) {
        cmbRole1.removeAllItems();
        for (Role r : o.getRole()) {
            cmbRole1.addItem(r);
        }
    }

    public void fillCmbEmp(Organization o) {
        cmbEmp1.removeAllItems();
        for (Employee e : o.getEmpRepo().getE_Repo()) {
            cmbEmp1.addItem(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new javax.swing.JScrollPane();
        tblAcc = new javax.swing.JTable();
        labelHeader1 = new javax.swing.JLabel();
        labelRole = new javax.swing.JLabel();
        cmbEmp1 = new javax.swing.JComboBox();
        cmbRole1 = new javax.swing.JComboBox();
        cmbOrg1 = new javax.swing.JComboBox();
        labelPwd = new javax.swing.JLabel();
        labelEmp = new javax.swing.JLabel();
        labelUsr = new javax.swing.JLabel();
        txtfieldUsr = new javax.swing.JTextField();
        labelOrg1 = new javax.swing.JLabel();
        txtfieldPwd = new javax.swing.JTextField();
        buttonCreate = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        scrollPane1.setBackground(new java.awt.Color(153, 204, 255));

        tblAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane1.setViewportView(tblAcc);

        labelHeader1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelHeader1.setForeground(new java.awt.Color(0, 51, 153));
        labelHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader1.setText("Manage User Account");

        labelRole.setText("Role");

        cmbEmp1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmp1ActionPerformed(evt);
            }
        });

        cmbRole1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRole1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRole1ActionPerformed(evt);
            }
        });

        cmbOrg1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrg1ActionPerformed(evt);
            }
        });

        labelPwd.setText("Password      :");

        labelEmp.setText("Employee");

        labelUsr.setText("User Name    :");

        txtfieldUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldUsrActionPerformed(evt);
            }
        });

        labelOrg1.setText("Organization");

        txtfieldPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldPwdActionPerformed(evt);
            }
        });

        buttonCreate.setBackground(new java.awt.Color(0, 102, 204));
        buttonCreate.setForeground(new java.awt.Color(255, 255, 255));
        buttonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        buttonCreate.setText("Create Account");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        buttonBack.setBackground(new java.awt.Color(0, 102, 204));
        buttonBack.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setText("<< Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelUsr)
                                    .addComponent(labelPwd))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfieldUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelOrg1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEmp1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbRole1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRole, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader1)
                .addGap(18, 18, 18)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelRole, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(labelEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelOrg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEmp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRole1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsr)
                    .addComponent(txtfieldUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPwd)
                    .addComponent(txtfieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrg1ActionPerformed
        Organization o = (Organization) cmbOrg1.getSelectedItem();
        if (o!=null){
            fillCmbEmp(o);
            fillCmbRole(o);
        }// TODO add your handling code here:
    }//GEN-LAST:event_cmbOrg1ActionPerformed

    private void cmbRole1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRole1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRole1ActionPerformed

    private void cmbEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmp1ActionPerformed

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        // TODO add your handling code here:
        String usrname = txtfieldUsr.getText();
        String pwd = txtfieldPwd.getText();
        Organization o = (Organization) cmbOrg1.getSelectedItem();
        Employee e = (Employee) cmbEmp1.getSelectedItem();
        Role r = (Role) cmbRole1.getSelectedItem();
        o.getUserAccDir().createUserAccount(usrname, pwd, e, r);
        fillRows();
    }//GEN-LAST:event_buttonCreateActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:

        panel.remove(this);
        CardLayout lout = (CardLayout) panel.getLayout();
        lout.previous(panel);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void txtfieldUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldUsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldUsrActionPerformed

    private void txtfieldPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldPwdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JComboBox cmbEmp1;
    private javax.swing.JComboBox cmbOrg1;
    private javax.swing.JComboBox cmbRole1;
    private javax.swing.JLabel labelEmp;
    private javax.swing.JLabel labelHeader1;
    private javax.swing.JLabel labelOrg1;
    private javax.swing.JLabel labelPwd;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelUsr;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JTable tblAcc;
    private javax.swing.JTextField txtfieldPwd;
    private javax.swing.JTextField txtfieldUsr;
    // End of variables declaration//GEN-END:variables
}
