/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Role_HospitalAdmin;

import Model.Employee;
import Model.Organization.RepositoryOrganization;
import Model.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshinichandrika
 */
public class ManagePanel_Employee extends javax.swing.JPanel {
    
    private RepositoryOrganization dirOrg;
    private JPanel panel;

    /**
     * Creates new form ManagePanel_Employee
     */
    public ManagePanel_Employee(JPanel p, RepositoryOrganization od) {
        initComponents();

    this.dirOrg =  od;
this.panel = p ;
        fillCmbOrg();
        fillCmbEmp();
    }
    
     public void fillCmbOrg() {
        cmbOrg1.removeAllItems();
        
        for (Organization o : dirOrg.getOrganizations()){
            cmbOrg1.addItem(o);
        }}

  
    public void fillCmbEmp() {
        cmbBoxOrg2.removeAllItems();
        
        for (Organization o : dirOrg.getOrganizations()){
            cmbBoxOrg2.addItem(o);
        }
    }
    
    private void fillRows(Organization o){
        DefaultTableModel m = (DefaultTableModel) tblEmp.getModel();
        m.setRowCount(0);
        for (Employee e : o.getEmpRepo().getE_Repo()){
            Object[] r = new Object[2];
            r[0] = e.getEId();
            r[1] = e.getEName();
            m.addRow(r);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbOrg1 = new javax.swing.JComboBox();
        labelOrg2 = new javax.swing.JLabel();
        cmbBoxOrg2 = new javax.swing.JComboBox();
        scrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        labelHeader1 = new javax.swing.JLabel();
        labelOrg1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        txtfieldName = new javax.swing.JTextField();
        buttonBack = new javax.swing.JButton();
        buttonCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        cmbOrg1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrg1ActionPerformed(evt);
            }
        });

        labelOrg2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelOrg2.setForeground(new java.awt.Color(0, 51, 153));
        labelOrg2.setText("Organization:");

        cmbBoxOrg2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBoxOrg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxOrg2ActionPerformed(evt);
            }
        });

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane1.setViewportView(tblEmp);

        labelHeader1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelHeader1.setForeground(new java.awt.Color(0, 51, 153));
        labelHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader1.setText("Manage Employee");

        labelOrg1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelOrg1.setForeground(new java.awt.Color(0, 51, 153));
        labelOrg1.setText("Organization");

        labelName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelName.setForeground(new java.awt.Color(0, 51, 153));
        labelName.setText("Name:");

        buttonBack.setBackground(new java.awt.Color(0, 51, 153));
        buttonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setText("<< Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonCreate.setBackground(new java.awt.Color(0, 51, 153));
        buttonCreate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCreate.setForeground(new java.awt.Color(255, 255, 255));
        buttonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        buttonCreate.setText("Create Employee");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelOrg2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbBoxOrg2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(labelOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonBack)
                        .addGap(55, 55, 55)
                        .addComponent(buttonCreate)
                        .addGap(308, 308, 308))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(labelOrg1)
                .addGap(18, 18, 18)
                .addComponent(cmbOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbBoxOrg2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOrg2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfieldName))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCreate))
                .addGap(46, 46, 46))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(labelHeader1)
                    .addContainerGap(666, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrg1ActionPerformed
        Organization o = (Organization) cmbOrg1.getSelectedItem();
        if (o != null){
            fillRows(o);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrg1ActionPerformed

    private void cmbBoxOrg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxOrg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxOrg2ActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        panel.remove(this);
        CardLayout l = (CardLayout) panel.getLayout();
        l.previous(panel);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        Organization o = (Organization) cmbBoxOrg2.getSelectedItem();
        String s = txtfieldName.getText();

        o.getEmpRepo().AddEmployee(s); 
         // TODO add your handling code here:
       JOptionPane.showMessageDialog(this, "Employee added successfully");
        fillRows(o);
    }//GEN-LAST:event_buttonCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JComboBox cmbBoxOrg2;
    private javax.swing.JComboBox cmbOrg1;
    private javax.swing.JLabel labelHeader1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelOrg1;
    private javax.swing.JLabel labelOrg2;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTextField txtfieldName;
    // End of variables declaration//GEN-END:variables
}
