/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Role_HospitalAdmin;

import Model.EnterPrise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author harshinichandrika
 */
public class WorkAreaPanel_Admin extends javax.swing.JPanel {
    
    JPanel panel;
    EnterPrise enterprise;

    /**
     * Creates new form WorkAreaPanel_Admin
     */
    public WorkAreaPanel_Admin(JPanel panel, EnterPrise e) {
        initComponents();
        this.panel=panel;
        this.enterprise=e;
        labelVal.setText(enterprise.getOrgName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeader1 = new javax.swing.JLabel();
        labelVal = new javax.swing.JLabel();
        labelEnt = new javax.swing.JLabel();
        buttonOrgMng = new javax.swing.JButton();
        buttonMngEmp = new javax.swing.JButton();
        ButtonMngUsr = new javax.swing.JButton();
        jpanelLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        labelHeader1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelHeader1.setForeground(new java.awt.Color(0, 51, 153));
        labelHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader1.setText("Hospital Work Area - Administrative Role");

        labelVal.setForeground(new java.awt.Color(0, 51, 153));
        labelVal.setText("<Value>");

        labelEnt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelEnt.setForeground(new java.awt.Color(0, 51, 153));
        labelEnt.setText("Enterprise : ");

        buttonOrgMng.setBackground(new java.awt.Color(0, 51, 153));
        buttonOrgMng.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrgMng.setText("Manage Organization");
        buttonOrgMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrgMngActionPerformed(evt);
            }
        });

        buttonMngEmp.setBackground(new java.awt.Color(0, 51, 153));
        buttonMngEmp.setForeground(new java.awt.Color(255, 255, 255));
        buttonMngEmp.setText("Manage Employee");
        buttonMngEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMngEmpActionPerformed(evt);
            }
        });

        ButtonMngUsr.setBackground(new java.awt.Color(0, 51, 153));
        ButtonMngUsr.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMngUsr.setText("Manage User");
        ButtonMngUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMngUsrActionPerformed(evt);
            }
        });

        jpanelLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage.png"))); // NOI18N
        jpanelLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jpanelLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonOrgMng, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMngEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonMngUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEnt)
                                .addGap(18, 18, 18)
                                .addComponent(labelVal))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEnt)
                            .addComponent(labelVal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonOrgMng)
                        .addGap(53, 53, 53)
                        .addComponent(buttonMngEmp)
                        .addGap(55, 55, 55)
                        .addComponent(ButtonMngUsr))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jpanelLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOrgMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrgMngActionPerformed
        ManagePanel_Organization m = new ManagePanel_Organization(panel, enterprise.getOrgaDirectory());
        panel.add("managePanel_Organization", m);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_buttonOrgMngActionPerformed

    private void buttonMngEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMngEmpActionPerformed
        ManagePanel_Employee m = new ManagePanel_Employee(panel, enterprise.getOrgaDirectory());
        panel.add("managePanel_Employee", m);
        CardLayout lyt = (CardLayout) panel.getLayout();
        lyt.next(panel);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMngEmpActionPerformed

    private void ButtonMngUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMngUsrActionPerformed
        ManagePanel_Account  m = new   ManagePanel_Account(panel, enterprise) ;
        panel.add("managePanel_Account",m);
        CardLayout cly = (CardLayout) panel.getLayout();
        cly.next(panel);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMngUsrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonMngUsr;
    private javax.swing.JButton buttonMngEmp;
    private javax.swing.JButton buttonOrgMng;
    private javax.swing.JLabel jpanelLabel1;
    private javax.swing.JLabel labelEnt;
    private javax.swing.JLabel labelHeader1;
    private javax.swing.JLabel labelVal;
    // End of variables declaration//GEN-END:variables
}
