/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Account;
import Model.DB4OUtil.DB4OUtil;
import Model.EcoSystem;
import Model.EnterPrise;
import Model.Network;
import Model.Organization.Organization;
import UI.Role_MedicalWaste.WorkAreaPanel_MedicalWaste;
import UI.Staff.WorkAreaPanelStaff;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author srikanthchilaka
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private EcoSystem eco;
    private Network net;
    private DB4OUtil db = DB4OUtil.getInstance();
    

    public MainJFrame() {
        initComponents();
        eco = db.retrieveSystem();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        loginPanel = new javax.swing.JPanel();
        labelImage1 = new javax.swing.JLabel();
        labelusername1 = new javax.swing.JLabel();
        textusername = new javax.swing.JTextField();
        labelpassword = new javax.swing.JLabel();
        labelimage2 = new javax.swing.JLabel();
        buttonback = new javax.swing.JButton();
        buttonlogout = new javax.swing.JButton();
        txtfieldpassword = new javax.swing.JPasswordField();
        containerpanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        splitPane.setDividerLocation(150);

        loginPanel.setBackground(new java.awt.Color(0, 102, 204));

        labelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doctor.png"))); // NOI18N

        labelusername1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        labelusername1.setForeground(new java.awt.Color(255, 255, 255));
        labelusername1.setText("Username");

        textusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textusernameActionPerformed(evt);
            }
        });

        labelpassword.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        labelpassword.setForeground(new java.awt.Color(255, 255, 255));
        labelpassword.setText("Password");

        labelimage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hospital.png"))); // NOI18N

        buttonback.setText("Login");
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });

        buttonlogout.setText("Logout");
        buttonlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(labelusername1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textusername)
                    .addComponent(labelpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelimage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfieldpassword))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(labelusername1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(buttonback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonlogout)
                .addGap(12, 12, 12)
                .addComponent(labelimage2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(loginPanel);

        containerpanel1.setBackground(new java.awt.Color(153, 204, 255));
        containerpanel1.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(containerpanel1);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textusernameActionPerformed

    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbackActionPerformed
        // TODO add your handling code here:
        String usr = textusername.getText();
        char[] arr = txtfieldpassword.getPassword();
        String pwd = String.valueOf(arr);

        Account acc = eco.getUserAccDir().validateAccount(usr, pwd);
        EnterPrise ent = null;
        Organization orgz = null;
        Network net = null;

        if (acc == null) {
            for (Network n : eco.getNetworks()) {
                for (EnterPrise e : n.getEnterpriseRepo().getEnterpRepo()) {
                    acc = e.getUserAccDir().validateAccount(usr, pwd);
                    if (acc == null) {
                        for (Organization org : e.getOrgaDirectory().getOrganizations()) {
                            acc = org.getUserAccDir().validateAccount(usr, pwd);
                            if (acc != null) {
                                net = n;
                                ent = e;
                                orgz = org;
                                System.out.println("***" + n.getNetwork_name());
                                break;
                            }
                        }
                    } else {
                        ent = e;
                        break;

                    }
                    if (orgz != null) {
                        break;
                    }
                }
                if (ent != null) {
                    break;
                }
            }
        }
// TODO add your handling code here:
        if (acc != null) {
//error casting
            CardLayout layout = (CardLayout) containerpanel1.getLayout();
            containerpanel1.add(acc.getRole().toString() + "workArea", acc.getRole().createWorkArea(containerpanel1, acc, orgz, ent, eco, net));
            layout.next(containerpanel1);
        } else {
            if (usr.equalsIgnoreCase("mw")) {
                WorkAreaPanel_MedicalWaste mwp = new WorkAreaPanel_MedicalWaste(null, null, null, null);
                CardLayout layout = (CardLayout) containerpanel1.getLayout();
                containerpanel1.add(mwp);
                layout.next(containerpanel1);
            } else if (usr.equalsIgnoreCase("st")) {
                WorkAreaPanelStaff mwp = new WorkAreaPanelStaff();
                CardLayout layout = (CardLayout) containerpanel1.getLayout();
                containerpanel1.add(mwp);
                layout.next(containerpanel1);
            } else {
                JOptionPane.showMessageDialog(null, "Credentials invalid");
                return;
            }
        }
        labelusername1.setEnabled(false);
        buttonback.setEnabled(false);
        labelpassword.setEnabled(false);
        buttonlogout.setEnabled(true);
    }//GEN-LAST:event_buttonbackActionPerformed

    private void buttonlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlogoutActionPerformed
        // TODO add your handling code here:
        buttonlogout.setEnabled(false);
        textusername.setText("");
        txtfieldpassword.setText("");
        textusername.setEnabled(true);
        db.storeSystem(eco);
        buttonback.setEnabled(true);
        containerpanel1.removeAll();
        txtfieldpassword.setEnabled(true);
        JPanel p = new JPanel();
        containerpanel1.add("blank", p);
        CardLayout layoutCard = (CardLayout) containerpanel1.getLayout();
        layoutCard.next(containerpanel1);
        db.storeSystem(eco);
    }//GEN-LAST:event_buttonlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonback;
    private javax.swing.JButton buttonlogout;
    private javax.swing.JPanel containerpanel1;
    private javax.swing.JLabel labelImage1;
    private javax.swing.JLabel labelimage2;
    private javax.swing.JLabel labelpassword;
    private javax.swing.JLabel labelusername1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField textusername;
    private javax.swing.JPasswordField txtfieldpassword;
    // End of variables declaration//GEN-END:variables
}
