/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Role_Supplier;

import Model.WorkQueue.Supplier_WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author harshinichandrika
 */
public class ManageWorkRequestPanel_Supplier extends javax.swing.JPanel {
    
    JPanel panel;
    Supplier_WorkRequest swq;

    /**
     * Creates new form ManageWorkRequestPanel_Supplier
     */
    public ManageWorkRequestPanel_Supplier(JPanel panel,Supplier_WorkRequest swq) {
        initComponents();
        this.panel = panel;
        this.swq = swq;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeader = new javax.swing.JLabel();
        labeldod = new javax.swing.JLabel();
        txtfieldDate = new javax.swing.JTextField();
        buttonBack = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(0, 51, 153));
        labelHeader.setText("PROCESSING SUPPLIER REQUEST");

        labeldod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labeldod.setForeground(new java.awt.Color(0, 51, 153));
        labeldod.setText("Select Date of Delivery:");

        buttonBack.setBackground(new java.awt.Color(0, 51, 153));
        buttonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setText("<<Back");

        buttonUpdate.setBackground(new java.awt.Color(0, 51, 153));
        buttonUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        buttonUpdate.setText("Update Status");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supplier.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelHeader)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeldod)
                            .addComponent(buttonBack))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonUpdate)
                            .addComponent(txtfieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHeader)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeldod)
                    .addComponent(txtfieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBack)
                    .addComponent(buttonUpdate))
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        swq.setStatus("Finished");
        JOptionPane.showMessageDialog(null, "Successfully updated the request!");        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labeldod;
    private javax.swing.JTextField txtfieldDate;
    // End of variables declaration//GEN-END:variables
}
