/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Role_Supplier;

import Model.Account;
import Model.EcoSystem;
import Model.Organization.Organization;
import Model.Organization.SupplierOrganization;
import Model.WorkQueue.Supplier_WorkRequest;
import Model.WorkQueue.Work_Request;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshinichandrika
 */
public class WorkAreaPanel_Supplier extends javax.swing.JPanel {
    
    private SupplierOrganization os;
    private JPanel panel;
    private Account acc;
    private EcoSystem eco;
    

    /**
     * Creates new form WorkAreaPanel_Supplier
     */
    public WorkAreaPanel_Supplier(JPanel panel, EcoSystem eco, Account acc, Organization o) {
        initComponents();
        this.panel = panel;
        this.acc = acc;
        this.eco = eco;
        this.os = (SupplierOrganization)o ;
        fillRows();
    }
    
    private void fillRows() {
        DefaultTableModel m = (DefaultTableModel)tabblesupplier.getModel();
        m.setRowCount(0);
        
        for(Work_Request wq : os.getWQ().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = ((Supplier_WorkRequest) wq);
            row[1]=((Supplier_WorkRequest) wq).getQuantity();
            row[2] = wq.getSender().getEmp().getEName();
            row[3] = wq.getReceiver() != null ? wq.getReceiver().getEmp().getEName() : null;
            row[4] = wq.getStatus();
            row[5]=((Supplier_WorkRequest) wq).getDeliveryTime();
            m.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonprocess = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        labelHeader2 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tabblesupplier = new javax.swing.JTable();
        buttonBack = new javax.swing.JButton();
        buttonAssign = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        buttonprocess.setBackground(new java.awt.Color(0, 51, 153));
        buttonprocess.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonprocess.setForeground(new java.awt.Color(255, 255, 255));
        buttonprocess.setText("Process");
        buttonprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonprocessActionPerformed(evt);
            }
        });

        buttonRefresh.setBackground(new java.awt.Color(0, 51, 153));
        buttonRefresh.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonRefresh.setForeground(new java.awt.Color(255, 255, 255));
        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        labelHeader2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelHeader2.setForeground(new java.awt.Color(0, 51, 153));
        labelHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader2.setText("SUPPLIER WORK AREA ");

        tabblesupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Quantity", "Sender", "Receiver", "Status", "Delivery Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(tabblesupplier);

        buttonBack.setBackground(new java.awt.Color(0, 51, 153));
        buttonBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setText("<<Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonAssign.setBackground(new java.awt.Color(0, 51, 153));
        buttonAssign.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonAssign.setForeground(new java.awt.Color(255, 255, 255));
        buttonAssign.setText("Assign to me");
        buttonAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAssignActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supplier.jpg"))); // NOI18N
        jLabel3.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonBack)
                        .addGap(99, 99, 99)
                        .addComponent(buttonAssign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonprocess, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(buttonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader2))
                .addGap(26, 26, 26)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRefresh)
                    .addComponent(buttonprocess)
                    .addComponent(buttonAssign)
                    .addComponent(buttonBack))
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonprocessActionPerformed

        int clicked = tabblesupplier.getSelectedRow();

        if (clicked < 0){
            return;
        }

        Supplier_WorkRequest sq = (Supplier_WorkRequest)tabblesupplier.getValueAt(clicked, 0);

        sq.setStatus("Processing");

        ManageWorkRequestPanel_Supplier mp = new ManageWorkRequestPanel_Supplier(panel, sq);
        panel.add("ManageWorkRequestPanel_Supplier", mp);
        CardLayout l = (CardLayout) panel.getLayout();
        l.next(panel);
    }//GEN-LAST:event_buttonprocessActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed

        fillRows();
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAssignActionPerformed

        int clicked = tabblesupplier.getSelectedRow();

        if (clicked < 0){
            return;
        }

        Work_Request wq = (Work_Request)tabblesupplier.getValueAt(clicked, 0);
        wq.setReceiver(acc);
        wq.setStatus("Assigned");
        fillRows();
    }//GEN-LAST:event_buttonAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAssign;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonprocess;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelHeader2;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabblesupplier;
    // End of variables declaration//GEN-END:variables
}
