/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Role_Administration;

import Model.Organization.RepositoryOrganization;
import Model.Organization.Organization;
import Model.Organization.Organization.OrganizationType;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srikanthchilaka
 */
public class ManagePanel_Organization extends javax.swing.JPanel {
    
    private RepositoryOrganization od;
    private JPanel panel;

    /**
     * Creates new form ManagePanel_Account
     */
    public ManagePanel_Organization(JPanel panel, RepositoryOrganization od) {
        initComponents();
        this.panel = panel;
        this.od = od;

        fillRows();
        fillCmb();
    }
    
    private void fillRows() {
        DefaultTableModel m = (DefaultTableModel) tblOrg.getModel();

        m.setRowCount(0);

        for (Organization o : od.getOrganizations()) {
            Object[] r = new Object[2];
            r[0] = o.getOrgId();
            r[1] = o.getOrgName();

            m.addRow(r);
        }
    }

    private void fillCmb() {
        cmbBoxOrg.removeAllItems();
        for (OrganizationType t : Organization.OrganizationType.values()) {
            if (!OrganizationType.Admin.getValue().equals(t.getValue())) {
                cmbBoxOrg.addItem(t);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonBack = new javax.swing.JButton();
        buttonCreateOrg = new javax.swing.JButton();
        scrollPane2 = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();
        labelHeader = new javax.swing.JLabel();
        labelOrg1 = new javax.swing.JLabel();
        cmbBoxOrg = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(153, 204, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        buttonBack.setBackground(new java.awt.Color(0, 51, 153));
        buttonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setText("<< Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonCreateOrg.setBackground(new java.awt.Color(0, 51, 153));
        buttonCreateOrg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCreateOrg.setForeground(new java.awt.Color(255, 255, 255));
        buttonCreateOrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R.png"))); // NOI18N
        buttonCreateOrg.setText("Add Organization");
        buttonCreateOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateOrgActionPerformed(evt);
            }
        });

        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane2.setViewportView(tblOrg);

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(0, 51, 153));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader.setText("Manage Organization");

        labelOrg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelOrg1.setText("Organization Type:");

        cmbBoxOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(labelOrg1)
                        .addGap(34, 34, 34)
                        .addComponent(cmbBoxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                                .addComponent(buttonCreateOrg))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                                .addComponent(labelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader)
                .addGap(62, 62, 62)
                .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrg1)
                    .addComponent(cmbBoxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCreateOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        panel.remove(this);
        CardLayout crd = (CardLayout) panel.getLayout();
        crd.previous(panel); // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonCreateOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateOrgActionPerformed
        OrganizationType t = (OrganizationType) cmbBoxOrg.getSelectedItem();
        od.addOrg(t);
        fillRows();  // TODO add your handling code here:
    }//GEN-LAST:event_buttonCreateOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCreateOrg;
    private javax.swing.JComboBox cmbBoxOrg;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelOrg1;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JTable tblOrg;
    // End of variables declaration//GEN-END:variables
}
