/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Role_Administration;

import Model.Account;
import Model.Employee;
import Model.EnterPrise;
import Model.Organization.Organization;
import Model.Role.Role;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srikanthchilaka
 */
public class ManagePanel_Account extends javax.swing.JPanel {
    
    private JPanel panel;
    private EnterPrise enterprise;

    /**
     * Creates new form ManagePanel_Organization
     */
    public ManagePanel_Account(JPanel panel, EnterPrise e) {
        initComponents();
        this.enterprise = e;
        this.panel = panel;
        fillOrgCmb(); // employeeJComboBox.removeAllItems();
        fillData();
    }
    
    public void fillOrgCmb() {
        cmbBoxOrg.removeAllItems();

        for (Organization organization : enterprise.getOrgaDirectory().getOrganizations()) {
            cmbBoxOrg.addItem(organization);
        }
    }

    public void fillEmpCmb(Organization o) {
        cmbBoxEmp.removeAllItems();

        for (Employee e : o.getEmpRepo().getE_Repo()) {
            cmbBoxEmp.addItem(e);
        }
    }

    public void fillRoleCmb(Organization o) {
        cmbBoxRole.removeAllItems();
        for (Role role : o.getRole()) {
            cmbBoxRole.addItem(role);
        }
    }
    
    public void fillData() {
        DefaultTableModel m = (DefaultTableModel) tblAcc.getModel();

        m.setRowCount(0);

        for (Organization o : enterprise.getOrgaDirectory().getOrganizations()) {
            for (Account a : o.getUserAccDir().getAccountList()) {
                Object row[] = new Object[2];
                row[0] = a;
                row[1] = a.getRole();
                ((DefaultTableModel) tblAcc.getModel()).addRow(row);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeader1 = new javax.swing.JLabel();
        scrollPane1 = new javax.swing.JScrollPane();
        tblAcc = new javax.swing.JTable();
        labelorg1 = new javax.swing.JLabel();
        cmbBoxOrg = new javax.swing.JComboBox();
        labelEmp = new javax.swing.JLabel();
        labelUsr = new javax.swing.JLabel();
        labelPwd = new javax.swing.JLabel();
        labelRole = new javax.swing.JLabel();
        cmbBoxRole = new javax.swing.JComboBox();
        cmbBoxEmp = new javax.swing.JComboBox();
        txtfieldUser = new javax.swing.JTextField();
        txtfieldPwd = new javax.swing.JTextField();
        buttonback = new javax.swing.JButton();
        buttonCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        labelHeader1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelHeader1.setForeground(new java.awt.Color(0, 51, 153));
        labelHeader1.setText("Manage User Account");

        tblAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane1.setViewportView(tblAcc);

        labelorg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelorg1.setText("Organization");

        cmbBoxOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBoxOrg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbBoxOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxOrgActionPerformed(evt);
            }
        });

        labelEmp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEmp.setText("Employee");

        labelUsr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelUsr.setText("User Name:");

        labelPwd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPwd.setText("Password:");

        labelRole.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelRole.setText("Role");

        cmbBoxRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBoxRole.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxRoleActionPerformed(evt);
            }
        });

        cmbBoxEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBoxEmp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbBoxEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxEmpActionPerformed(evt);
            }
        });

        txtfieldPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldPwdActionPerformed(evt);
            }
        });

        buttonback.setBackground(new java.awt.Color(0, 51, 153));
        buttonback.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonback.setForeground(new java.awt.Color(255, 255, 255));
        buttonback.setText("<< Back");
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });

        buttonCreate.setBackground(new java.awt.Color(0, 51, 153));
        buttonCreate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCreate.setForeground(new java.awt.Color(255, 255, 255));
        buttonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        buttonCreate.setText("Create User Account");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelHeader1)
                .addGap(297, 297, 297))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(labelorg1)
                .addGap(123, 123, 123)
                .addComponent(labelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(labelRole, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonback, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtfieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelUsr)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtfieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(138, 138, 138))
                                    .addComponent(buttonCreate, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbBoxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(cmbBoxEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(labelHeader1)
                .addGap(75, 75, 75)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelorg1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRole, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonback)
                    .addComponent(buttonCreate))
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBoxOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxOrgActionPerformed
        Organization o = (Organization) cmbBoxOrg.getSelectedItem();
        if (o != null){
            fillEmpCmb(o);
            fillRoleCmb(o);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxOrgActionPerformed

    private void cmbBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxRoleActionPerformed

    private void cmbBoxEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxEmpActionPerformed

    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbackActionPerformed
        panel.remove(this);
        CardLayout l = (CardLayout) panel.getLayout();
        l.previous(panel);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonbackActionPerformed

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        String usrnm = txtfieldUser.getText();
        String pwd = txtfieldPwd.getText();
        Organization organization = (Organization) cmbBoxOrg.getSelectedItem();
        Employee e = (Employee) cmbBoxEmp.getSelectedItem();
        Role r = (Role) cmbBoxRole.getSelectedItem();
        organization.getUserAccDir().createUserAccount(usrnm, pwd, e, r);
        fillData();        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCreateActionPerformed

    private void txtfieldPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldPwdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreate;
    private javax.swing.JButton buttonback;
    private javax.swing.JComboBox cmbBoxEmp;
    private javax.swing.JComboBox cmbBoxOrg;
    private javax.swing.JComboBox cmbBoxRole;
    private javax.swing.JLabel labelEmp;
    private javax.swing.JLabel labelHeader1;
    private javax.swing.JLabel labelPwd;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelUsr;
    private javax.swing.JLabel labelorg1;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JTable tblAcc;
    private javax.swing.JTextField txtfieldPwd;
    private javax.swing.JTextField txtfieldUser;
    // End of variables declaration//GEN-END:variables
}
