/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Role_Administration;

import Model.EnterPrise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author srikanthchilaka
 */
public class WorkAreaPanel_Admin extends javax.swing.JPanel {
    
    JPanel panel;
    EnterPrise enterprise;

    /**
     * Creates new form WorkAreaPanel_Admin
     */
    public WorkAreaPanel_Admin(JPanel p, EnterPrise e) {
        initComponents();
        this.panel=p;
        this.enterprise=e;
        labelValue.setText(e.getOrgName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeader = new javax.swing.JLabel();
        labelEnterprise = new javax.swing.JLabel();
        labelValue = new javax.swing.JLabel();
        buttonOrg = new javax.swing.JButton();
        buttonEmp = new javax.swing.JButton();
        buttonUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(0, 51, 153));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader.setText("My Work Area - Administrative Role");

        labelEnterprise.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelEnterprise.setText("Enterprise:");

        labelValue.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelValue.setText("<value>");

        buttonOrg.setBackground(new java.awt.Color(0, 51, 153));
        buttonOrg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonOrg.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrg.setText("Manage Organization");
        buttonOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrgActionPerformed(evt);
            }
        });

        buttonEmp.setBackground(new java.awt.Color(0, 51, 153));
        buttonEmp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonEmp.setForeground(new java.awt.Color(255, 255, 255));
        buttonEmp.setText("Manage Employee");
        buttonEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEmpActionPerformed(evt);
            }
        });

        buttonUser.setBackground(new java.awt.Color(0, 51, 153));
        buttonUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonUser.setForeground(new java.awt.Color(255, 255, 255));
        buttonUser.setText("Manage User");
        buttonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(345, 345, 345))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader)
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnterprise)
                    .addComponent(labelValue))
                .addGap(18, 18, 18)
                .addComponent(buttonOrg)
                .addGap(40, 40, 40)
                .addComponent(buttonEmp)
                .addGap(38, 38, 38)
                .addComponent(buttonUser)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrgActionPerformed
        UI.Role_HospitalAdmin.ManagePanel_Organization manageOrganizationPanel = new UI.Role_HospitalAdmin.ManagePanel_Organization(panel, enterprise.getOrgaDirectory());
        panel.add("manageOrganizationPanel", manageOrganizationPanel);
        CardLayout l = (CardLayout) panel.getLayout();
        l.next(panel);       // TODO add your handling code here:
    }//GEN-LAST:event_buttonOrgActionPerformed

    private void buttonEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEmpActionPerformed
        UI.Role_HospitalAdmin.ManagePanel_Employee manageEmployeePanel = new UI.Role_HospitalAdmin.ManagePanel_Employee(panel, enterprise.getOrgaDirectory());
        panel.add("manageEmployeePanel", manageEmployeePanel);
        CardLayout l = (CardLayout) panel.getLayout();
        l.next(panel);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEmpActionPerformed

    private void buttonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserActionPerformed
        UI.Role_HospitalAdmin.ManagePanel_Account  manageAccountPanel = new UI.Role_HospitalAdmin.ManagePanel_Account(panel, enterprise);
        panel.add("manageAccountPanel",manageAccountPanel);
        CardLayout l = (CardLayout) panel.getLayout();
        l.next(panel);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEmp;
    private javax.swing.JButton buttonOrg;
    private javax.swing.JButton buttonUser;
    private javax.swing.JLabel labelEnterprise;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelValue;
    // End of variables declaration//GEN-END:variables
}
