/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.SysAdminList;
import model.SystemAdmin;

/**
 *
 * @author srikanthchilaka
 */
public class CreateSysAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateSysAJPanel
     */
    SysAdminList sAdmin;
    public CreateSysAJPanel(SysAdminList sAdmin) {
        initComponents();
        this.sAdmin = sAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSysAID = new javax.swing.JLabel();
        lblSysAName = new javax.swing.JLabel();
        lblSysAuname = new javax.swing.JLabel();
        lblSysApswd = new javax.swing.JLabel();
        txtSysAID = new javax.swing.JTextField();
        txtSysAName = new javax.swing.JTextField();
        txtSysAUname = new javax.swing.JTextField();
        txtSysAPswd = new javax.swing.JTextField();
        btnSysASave = new javax.swing.JButton();
        lblSysA = new javax.swing.JLabel();

        lblSysAID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysAID.setText("ID:");

        lblSysAName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysAName.setText("Name:");

        lblSysAuname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysAuname.setText("Username:");

        lblSysApswd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysApswd.setText("Password:");

        txtSysAID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSysAIDActionPerformed(evt);
            }
        });

        btnSysASave.setText("Save");
        btnSysASave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSysASaveActionPerformed(evt);
            }
        });

        lblSysA.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblSysA.setText("System Admin Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSysAID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSysAName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSysAuname, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(lblSysApswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSysAID)
                            .addComponent(txtSysAName)
                            .addComponent(txtSysAUname)
                            .addComponent(txtSysAPswd, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnSysASave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblSysA, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblSysA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysAID)
                    .addComponent(txtSysAID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysAName)
                    .addComponent(txtSysAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysAuname)
                    .addComponent(txtSysAUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysApswd)
                    .addComponent(txtSysAPswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSysASave)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSysAIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSysAIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSysAIDActionPerformed
    public boolean isEmpty(String c){
        return c != null && c.length() ==0;
    }
    private void btnSysASaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSysASaveActionPerformed
        // TODO add your handling code here:
        if(sAdmin!=null){
            if(isEmpty(txtSysAID.getText())) {
                JOptionPane.showMessageDialog(this, "Please enter System Admin ID");
                return;
            }
            String systID = txtSysAID.getText();
            if(isEmpty(txtSysAName.getText())) {
                JOptionPane.showMessageDialog(this, "Please enter System Admin Name");
                return;
            }
            String systName = txtSysAName.getText();
            if(isEmpty(txtSysAUname.getText())) {
                JOptionPane.showMessageDialog(this, "Please enter System Admin Username");
                return;
            }
            String sysUname = txtSysAUname.getText();
            if(isEmpty(txtSysAPswd.getText())) {
                JOptionPane.showMessageDialog(this, "Please enter System Admin Password");
                return;
            }
            String sysPswd = txtSysAPswd.getText();
            SystemAdmin sysA = sAdmin.addNewSysA();
            
            sysA.setSysID(systID);
            sysA.setSysName(systName);
            sysA.setSysUsername(sysUname);
            sysA.setSysPassword(sysPswd);
            
            JOptionPane.showMessageDialog(this,"New System Admin Added");
    
            txtSysAID.setText("");
            txtSysAName.setText("");
            txtSysAUname.setText("");
            txtSysAPswd.setText("");
            
        }
        else{
            JOptionPane.showMessageDialog(this,"No Admin");
        }
    }//GEN-LAST:event_btnSysASaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSysASave;
    private javax.swing.JLabel lblSysA;
    private javax.swing.JLabel lblSysAID;
    private javax.swing.JLabel lblSysAName;
    private javax.swing.JLabel lblSysApswd;
    private javax.swing.JLabel lblSysAuname;
    private javax.swing.JTextField txtSysAID;
    private javax.swing.JTextField txtSysAName;
    private javax.swing.JTextField txtSysAPswd;
    private javax.swing.JTextField txtSysAUname;
    // End of variables declaration//GEN-END:variables
}
