/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SysAdminList;
import model.SystemAdmin;

/**
 *
 * @author srikanthchilaka
 */
public class ViewSysAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSysAJPanel
     */
    SysAdminList sAdmin;
    public ViewSysAJPanel() {
        initComponents();
        this.sAdmin = sAdmin;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSysAID = new javax.swing.JTextField();
        lblViewSysA = new javax.swing.JLabel();
        txtSysAName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSysA = new javax.swing.JTable();
        txtSysAUname = new javax.swing.JTextField();
        btnViewSysA = new javax.swing.JButton();
        btnDeleteSysA = new javax.swing.JButton();
        txtSysAPswd = new javax.swing.JTextField();
        lblSysAID = new javax.swing.JLabel();
        lblSysAName = new javax.swing.JLabel();
        lblSysAuname = new javax.swing.JLabel();
        lblSysApswd = new javax.swing.JLabel();

        txtSysAID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSysAIDActionPerformed(evt);
            }
        });

        lblViewSysA.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblViewSysA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewSysA.setText("View System Administrator Details");

        tblSysA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblSysA);

        txtSysAUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSysAUnameActionPerformed(evt);
            }
        });

        btnViewSysA.setText("View");
        btnViewSysA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSysAActionPerformed(evt);
            }
        });

        btnDeleteSysA.setText("Delete");
        btnDeleteSysA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSysAActionPerformed(evt);
            }
        });

        txtSysAPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSysAPswdActionPerformed(evt);
            }
        });

        lblSysAID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysAID.setText("ID:");

        lblSysAName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysAName.setText("Name:");

        lblSysAuname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysAuname.setText("Username:");

        lblSysApswd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysApswd.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblViewSysA, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewSysA)
                        .addGap(63, 63, 63)
                        .addComponent(btnDeleteSysA))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSysAuname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSysApswd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSysAName)
                            .addComponent(lblSysAID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSysAPswd)
                            .addComponent(txtSysAUname)
                            .addComponent(txtSysAName)
                            .addComponent(txtSysAID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewSysA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewSysA)
                    .addComponent(btnDeleteSysA))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysAID)
                    .addComponent(txtSysAID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysAName)
                    .addComponent(txtSysAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysAuname)
                    .addComponent(txtSysAUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysApswd)
                    .addComponent(txtSysAPswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSysAIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSysAIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSysAIDActionPerformed

    private void txtSysAUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSysAUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSysAUnameActionPerformed

    private void btnViewSysAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSysAActionPerformed
        // TODO add your handling code here:
        if(sAdmin!=null){
            int selectedRowIndex = tblSysA.getSelectedRow();
            if(selectedRowIndex<0){
                JOptionPane.showMessageDialog(this,"Please select a row to delete.");
                return;
            }
            DefaultTableModel model= (DefaultTableModel) tblSysA.getModel();
            SystemAdmin selectedSysAdmin = (SystemAdmin) model.getValueAt(selectedRowIndex, 0);
            txtSysAID.setText(selectedSysAdmin.getSysID());
            txtSysAName.setText(selectedSysAdmin.getSysName());
            txtSysAUname.setText(selectedSysAdmin.getSysUsername());
            txtSysAPswd.setText(selectedSysAdmin.getSysPassword());

        }
        else{
            JOptionPane.showMessageDialog(this,"Row empty.");
        }
    }//GEN-LAST:event_btnViewSysAActionPerformed

    private void btnDeleteSysAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSysAActionPerformed
        // TODO add your handling code here:
        if(sAdmin!=null){
            int selectedRowIndex = tblSysA.getSelectedRow();
            if(selectedRowIndex<0){
                JOptionPane.showMessageDialog(this,"Please select a row to delete.");
                return;
            }
            DefaultTableModel model= (DefaultTableModel) tblSysA.getModel();
            SystemAdmin selectedAdmin = (SystemAdmin) model.getValueAt(selectedRowIndex, 0);
            sAdmin.deleteSysA(selectedAdmin);
            JOptionPane.showMessageDialog(this, "System Admin deleted");
            populateTable();
        }
        else{
            JOptionPane.showMessageDialog(this,"Row empty.");
        }
    }//GEN-LAST:event_btnDeleteSysAActionPerformed

    private void txtSysAPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSysAPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSysAPswdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteSysA;
    private javax.swing.JButton btnViewSysA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSysAID;
    private javax.swing.JLabel lblSysAName;
    private javax.swing.JLabel lblSysApswd;
    private javax.swing.JLabel lblSysAuname;
    private javax.swing.JLabel lblViewSysA;
    private javax.swing.JTable tblSysA;
    private javax.swing.JTextField txtSysAID;
    private javax.swing.JTextField txtSysAName;
    private javax.swing.JTextField txtSysAPswd;
    private javax.swing.JTextField txtSysAUname;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
        DefaultTableModel model= (DefaultTableModel) tblSysA.getModel();
        model.setRowCount(0);
        
        for(SystemAdmin sa : sAdmin.getSAdmin()){
            Object[] row = new Object[4];
            row[0] = sa;
            row[1] = sa.getSysName();
            row[2] = sa.getSysUsername();
            row[3] = sa.getSysPassword();
            model.addRow(row);
        }
    }
}
