/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.UserInterface.HCEquipStorage;

import Model.Account;
import Model.EcoSystem;
import Model.EnterPrise;
import Model.Network;
import Model.Organization.Organization;
import Model.WorkQueue.HealthcareEquipmentWorkRequest;
import Model.WorkQueue.WorkRequest;
import Model.WorkQueue.TransportationWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author venkat
 */
public class HealthCareEquipmentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthCareEquipmentWorkAreaJPanel
     */

private JPanel upperContainer;
private EcoSystem eco;
private Account acc;
private Organization org ;
private Network ntk;
private Organization transportOrg;
private EnterPrise enter;
    public HealthCareEquipmentWorkAreaJPanel(JPanel uppercontainer,EcoSystem eco, Account acc,Organization org, Network ntk ) {
        initComponents();

   this.upperContainer = uppercontainer;
this.eco = eco;
this.acc = acc;
this.org = org;
this.ntk = ntk;
populateHealthCareReqTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonassign = new javax.swing.JButton();
        buttonback = new javax.swing.JButton();
        processrequestbutton = new javax.swing.JButton();
        viewrequeststatusbutton = new javax.swing.JButton();
        buttonrefresh = new javax.swing.JButton();
        mainbutton = new javax.swing.JLabel();
        jpanelscroll1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(900, 665));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonassign.setBackground(new java.awt.Color(0, 51, 153));
        buttonassign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonassign.setForeground(new java.awt.Color(255, 255, 255));
        buttonassign.setText("ASSIGN TO ME");
        buttonassign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonassignActionPerformed(evt);
            }
        });
        add(buttonassign, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 167, 43));

        buttonback.setBackground(new java.awt.Color(0, 51, 153));
        buttonback.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonback.setForeground(new java.awt.Color(255, 255, 255));
        buttonback.setText("<<Back");
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });
        add(buttonback, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 105, 43));

        processrequestbutton.setBackground(new java.awt.Color(0, 51, 153));
        processrequestbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        processrequestbutton.setForeground(new java.awt.Color(255, 255, 255));
        processrequestbutton.setText("PROCESS REQUEST>>>");
        processrequestbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processrequestbuttonActionPerformed(evt);
            }
        });
        add(processrequestbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 257, 43));

        viewrequeststatusbutton.setBackground(new java.awt.Color(0, 51, 153));
        viewrequeststatusbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewrequeststatusbutton.setForeground(new java.awt.Color(255, 255, 255));
        viewrequeststatusbutton.setText("VIEW REQUEST STATUS>>");
        viewrequeststatusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrequeststatusbuttonActionPerformed(evt);
            }
        });
        add(viewrequeststatusbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, -1, 43));

        buttonrefresh.setBackground(new java.awt.Color(0, 51, 153));
        buttonrefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonrefresh.setForeground(new java.awt.Color(255, 255, 255));
        buttonrefresh.setText("Refresh");
        add(buttonrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, 36));

        mainbutton.setBackground(new java.awt.Color(153, 204, 255));
        mainbutton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        mainbutton.setForeground(new java.awt.Color(0, 51, 153));
        mainbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainbutton.setText("REQUESTS FROM HOSPITALS");
        add(mainbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -10, 648, 113));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EQUIPMENT NAME", "URGENCY LEVEL", "QUANTITY", "SENDER", "RECIEVER", "REQUEST SENT Y/N"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jpanelscroll1.setViewportView(jTable1);

        add(jpanelscroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 909, 279));

        jlabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steth.png"))); // NOI18N
        jlabel2.setText("jLabel1");
        add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 170, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonassignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonassignActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }

        HealthcareEquipmentWorkRequest request = (HealthcareEquipmentWorkRequest)jTable1.getValueAt(selectedRow, 0);
        request.setReceiver(acc);
        request.setStatus("Pending");
        request.setTransportrequestStatus("N");

        populateHealthCareReqTbl();        // TODO add your handling code here:
    }//GEN-LAST:event_buttonassignActionPerformed

    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbackActionPerformed
        upperContainer.remove(this);
        CardLayout layout = (CardLayout) upperContainer.getLayout();
        layout.previous(upperContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonbackActionPerformed

    private void processrequestbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processrequestbuttonActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }

        HealthcareEquipmentWorkRequest request = (HealthcareEquipmentWorkRequest)jTable1.getValueAt(selectedRow, 0);
        System.out.println("hello");
        request.setStatus("Request sent to transport department for delivery");
        TransportationWorkRequest transportrequest=new TransportationWorkRequest();
        transportrequest=new TransportationWorkRequest();
     transportrequest.setSender(acc);

        transportrequest.setHospitalName(request.getHospitalName());

        transportrequest.setUrgency(request.getUrgencyLevel());
        transportrequest.setStatus("Sent");
        transportrequest.setEquipmentinfo(("Name: "+request.getEquipmentName())+","+ "Qauntity: " +( request.getQuantity()));
        request.setExpectedArrivalTime(request.getMessage());
        request.setTransportrequestStatus("Y");
        if(ntk.getNetwork_Name().equals(this.ntk.getNetwork_Name())){
            for(EnterPrise enterprise :ntk.getDirectoEnterpri().getEnterpList() ){
                System.out.println("****" +enterprise.getOrgName());
                System.out.println("******"+enterprise.getEnterprise_type());
                for(Organization organization:enterprise.getOrgaDirectory().getOrganizations()){
                    System.out.println("***** Organization Name:" +organization.getOrgName());
                    if(organization.getOrgName().equals("Transportation Organization")){
                        System.out.println("True");
                        System.out.println("***** organization Name"+organization.getOrgName());
                        JOptionPane.showMessageDialog(null, "A Notification has been sent to concerned Transport Department "
                            + "The request id is : "+transportrequest.getUniqueId());
                        int requestId=transportrequest.getUniqueId();
                        System.out.println("***" +requestId);
                        transportrequest.setRequestId(requestId);
                        acc.getWorkQueue().getWorkRequestList().add(transportrequest);
                        organization.getWQ().getWorkRequestList().add(transportrequest);

                    }

                }
            }

            CardLayout layout = (CardLayout) upperContainer.getLayout();
            upperContainer.add("ProcessRequest", new ViewTransportationRequestJPanel(upperContainer,acc));
            layout.next(upperContainer);

        }
        else{
            CardLayout layout = (CardLayout) upperContainer.getLayout();
            upperContainer.add("ProcessRequest", new ViewTransportationRequestJPanel(upperContainer,acc));
            layout.next(upperContainer);

        }
        // populateTransportWorkRequest();
        // TODO add your handling code here:
    }//GEN-LAST:event_processrequestbuttonActionPerformed

    private void viewrequeststatusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrequeststatusbuttonActionPerformed
        CardLayout layout = (CardLayout) upperContainer.getLayout();
        upperContainer.add("ProcessRequest", new ViewTransportationRequestJPanel(upperContainer,acc));
        layout.next(upperContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_viewrequeststatusbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonassign;
    private javax.swing.JButton buttonback;
    private javax.swing.JButton buttonrefresh;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JScrollPane jpanelscroll1;
    private javax.swing.JLabel mainbutton;
    private javax.swing.JButton processrequestbutton;
    private javax.swing.JButton viewrequeststatusbutton;
    // End of variables declaration//GEN-END:variables

    private void populateHealthCareReqTbl() {
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

      DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        model.setRowCount(0);
        System.out.println(org.getWQ().getWorkRequestList().size());
        for(WorkRequest request : org.getWQ().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0]=((HealthcareEquipmentWorkRequest) request);
            String urgencyLevel = ((HealthcareEquipmentWorkRequest) request).getUrgencyLevel();
            int quantity = ((HealthcareEquipmentWorkRequest) request).getQuantity();
            row[1] = urgencyLevel;
            row[2]=quantity;
            row[3]=request.getSender().getUsrnm();
            
//            row[4]=request.getReceiver().getUsrnm();
            
            model.addRow(row);
        }
}
}




 /*public void populateTransportWorkRequest(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        model.setRowCount(0);
        Object row[]=new Object[4];
        for(WorkRequest request : acc.getWorkQueue().getWorkRequestList()){
            row[0]=((TransportationWorkRequest) request);
            row[1]=request.getReceiver();
            row[2]=request.getStatus();
            row[3]=((TransportationWorkRequest)request).getTime();
        }
        
    }
    }*/


